### ISSUE TITLE
Error: invalid entity id: undefined

### ISSUE THREAD

**Issue by mshd** [dataprick/wikitree#46]
https://tools.wmflabs.org/wikioverdata/wikitree/public/?q=Q7404563&level=4&type=descendants&orientation=North&lang=en&options%5Bsocialmedia%5D=on&options%5Bspouses%5D=on

Error: invalid entity id: undefined

**Comment by mshd** [comment]
(node:10315) UnhandledPromiseRejectionWarning: Error: invalid entity id: undefined
    at value (/home/martin/workspace/wikitree/node_modules/wikibase-sdk/lib/helpers/validate.js:4:40)
    at Array.forEach (<anonymous>)
    at /home/martin/workspace/wikitree/node_modules/wikibase-sdk/lib/queries/get_entities.js:18:7
    at getIdsGroups.map.idsGroup (/home/martin/workspace/wikitree/node_modules/wikibase-sdk/lib/queries/get_many_entities.js:14:22)
    at Array.map (<anonymous>)
    at Object.getManyEntities (/home/martin/workspace/wikitree/node_modules/wikibase-sdk/lib/queries/get_many_entities.js:14:6)
    at Object.exports.wikidataApi (/home/martin/workspace/wikitree/controllers/wikidata.js:16:22)
    at processLevel (/home/martin/workspace/wikitree/controllers/wikitree.js:302:32)
    at /home/martin/workspace/wikitree/controllers/wikitree.js:263:13
    at fetch.then.then.entities (/home/martin/workspace/wikitree/controllers/wikidata.js:30:17)
(node:10315) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by edwinindrajayas** [comment]
In the wikidata page https://www.wikidata.org/wiki/Q9543, the spouse property is exist, but it has no value.

**Comment by mshd** [comment]
Ah ok thanks for fixing

**Comment by mshd** [comment]
Maybe it should also work for children, if it's set to no value?
